"""Plant base class: the ground-truth process simulator.

Design contract (see project plan, section 5):

* The ``Plant`` is *the truth*. A controller never sees inside it; it only
  observes the (noisy) measurement returned by :meth:`Plant.step`.
* **All actuator saturation and all transport delay live here.** Every
  controller is therefore subject to identical physical limits, so any
  advantage MPC shows must come from *anticipating* a constraint, never from
  being exempt from one.
* Measurement noise is generated by a plant-owned RNG that is re-seeded on
  :meth:`reset`. Two controllers run on the same plant therefore see the exact
  same noise realisation -- a fairness requirement, not a nicety.

Subclasses implement the continuous-time dynamics ``xdot = f(x, u, d)`` and the
output map ``y = g(x)``; integration, delay, saturation and noise are handled
once, here.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections import deque

import numpy as np


def _as_array(value, n: int, name: str) -> np.ndarray:
    """Broadcast a scalar or sequence to a float array of length ``n``."""
    arr = np.atleast_1d(np.asarray(value, dtype=float))
    if arr.size == 1:
        arr = np.full(n, float(arr[0]))
    if arr.size != n:
        raise ValueError(f"{name} must have length {n}, got {arr.size}")
    return arr


class Plant(ABC):
    """Abstract ground-truth process."""

    n_states: int
    n_inputs: int
    n_outputs: int

    def __init__(
        self,
        *,
        n_states: int,
        n_inputs: int,
        n_outputs: int,
        u_min,
        u_max,
        x0,
        dead_time=0.0,
        n_disturbances: int = 1,
        d_dead_time=0.0,
        y_dead_time=0.0,
        noise_std=0.0,
        y_min=None,
        y_max=None,
        n_substeps: int = 4,
        seed: int = 0,
    ):
        self.n_states = int(n_states)
        self.n_inputs = int(n_inputs)
        self.n_outputs = int(n_outputs)

        self.u_min = _as_array(u_min, self.n_inputs, "u_min")
        self.u_max = _as_array(u_max, self.n_inputs, "u_max")
        if np.any(self.u_min >= self.u_max):
            raise ValueError("u_min must be strictly below u_max")

        # Transport (dead) time per input, in seconds. In process control this is
        # the single most damaging dynamic feature: it eats phase margin without
        # eating gain, so a feedback controller cannot react to what it has not
        # yet seen. Modelled as an input-side FIFO of past moves.
        self.dead_time = _as_array(dead_time, self.n_inputs, "dead_time")
        if np.any(self.dead_time < 0):
            raise ValueError("dead_time must be non-negative")

        # Transport delay on the *disturbance* path, which is generally not the
        # same as the delay on the manipulated path. The difference is what
        # decides whether feedforward compensation is realisable at all: the
        # disturbance must reach the output later than the valve does, or no
        # compensator can act in time. (Feed moisture measured on a belt and
        # arriving at the mill a minute later is the friendly case; a demand
        # change that hits the process before the valve can respond is not.)
        self.n_disturbances = int(n_disturbances)
        self.d_dead_time = _as_array(d_dead_time, self.n_disturbances, "d_dead_time")
        if np.any(self.d_dead_time < 0):
            raise ValueError("d_dead_time must be non-negative")

        # Measurement dead time, per output. Distinct from process dead time and
        # every bit as damaging: a thermowell, a chromatograph or an XRF
        # analyser reports what the process was doing minutes ago. It is also
        # what makes cascade control worth its extra transmitter -- the fast
        # secondary measurement is usually the *undelayed* one.
        self.y_dead_time = _as_array(y_dead_time, self.n_outputs, "y_dead_time")
        if np.any(self.y_dead_time < 0):
            raise ValueError("y_dead_time must be non-negative")

        self.noise_std = _as_array(noise_std, self.n_outputs, "noise_std")

        # Output limits are *reporting only* in phase 1: the plant does not
        # enforce them. They exist so the harness can count how often a
        # controller drives the process past a limit it was supposed to respect.
        self.y_min = None if y_min is None else _as_array(y_min, self.n_outputs, "y_min")
        self.y_max = None if y_max is None else _as_array(y_max, self.n_outputs, "y_max")

        self.x0 = np.atleast_1d(np.asarray(x0, dtype=float)).copy()
        if self.x0.size != self.n_states:
            raise ValueError(f"x0 must have length {self.n_states}")

        self.n_substeps = int(n_substeps)
        self.seed = int(seed)

        # Value the delay line is primed with; subclasses may override before
        # reset() so the pipeline starts at a consistent steady state.
        self.u_init = np.zeros(self.n_inputs)

        self._dt: float | None = None
        self._u_buffer: deque | None = None
        self._d_buffer: deque | None = None
        self._y_buffer: deque | None = None
        self.rng = np.random.default_rng(self.seed)
        self.x = self.x0.copy()
        self.t = 0.0

    # ------------------------------------------------------------------
    # to be implemented by concrete plants
    # ------------------------------------------------------------------
    @abstractmethod
    def dynamics(self, x: np.ndarray, u: np.ndarray, d: np.ndarray) -> np.ndarray:
        """Continuous-time state derivative ``xdot = f(x, u, d)``.

        ``u`` here is the *delayed, saturated* input actually reaching the
        process, not the raw controller output.
        """

    def output(self, x: np.ndarray) -> np.ndarray:
        """Noise-free output map ``y = g(x)``. Defaults to full state."""
        return x.copy()

    # ------------------------------------------------------------------
    # simulation interface
    # ------------------------------------------------------------------
    def reset(self, x0: np.ndarray | None = None, seed: int | None = None) -> np.ndarray:
        """Return the plant to its initial condition and re-seed the noise.

        Re-seeding here is what makes controller comparisons fair: run A and
        run B see bit-identical measurement noise.
        """
        self.x = self.x0.copy() if x0 is None else np.atleast_1d(np.asarray(x0, float)).copy()
        if self.x.size != self.n_states:
            raise ValueError(f"x0 must have length {self.n_states}")
        self.t = 0.0
        self.rng = np.random.default_rng(self.seed if seed is None else int(seed))
        self._dt = None
        self._u_buffer = None
        self._d_buffer = None
        self._y_buffer = None
        return self.measure()

    def measure(self) -> np.ndarray:
        """Noisy measurement of the current state."""
        y = np.atleast_1d(self.output(self.x)).astype(float)
        if np.any(self.noise_std > 0):
            y = y + self.rng.normal(0.0, self.noise_std)
        return y

    def saturate(self, u: np.ndarray) -> np.ndarray:
        """Clip a requested move to the actuator range."""
        return np.clip(np.atleast_1d(np.asarray(u, float)), self.u_min, self.u_max)

    def _init_delay(self, dt: float) -> None:
        n_delay = np.round(self.dead_time / dt).astype(int)
        self._delay_samples = n_delay
        self._u_buffer = deque(
            [self.u_init.copy() for _ in range(int(n_delay.max()) + 1)],
            maxlen=int(n_delay.max()) + 1,
        )
        n_delay_y = np.round(self.y_dead_time / dt).astype(int)
        self._y_delay_samples = n_delay_y
        y_now = np.atleast_1d(self.output(self.x)).astype(float)
        self._y_buffer = deque(
            [y_now.copy() for _ in range(int(n_delay_y.max()) + 1)],
            maxlen=int(n_delay_y.max()) + 1,
        )

        n_delay_d = np.round(self.d_dead_time / dt).astype(int)
        self._d_delay_samples = n_delay_d
        self._d_buffer = deque(
            [np.zeros(self.n_disturbances) for _ in range(int(n_delay_d.max()) + 1)],
            maxlen=int(n_delay_d.max()) + 1,
        )
        self._dt = float(dt)

    def _delayed_input(self, u_sat: np.ndarray, dt: float) -> np.ndarray:
        """Push the current move into the delay line, pop what arrives now."""
        if self._u_buffer is None:
            self._init_delay(dt)
        elif not np.isclose(dt, self._dt):
            raise ValueError(
                f"dt changed mid-run ({self._dt} -> {dt}); the delay line assumes a fixed sample time"
            )
        self._u_buffer.append(u_sat.copy())
        return np.array(
            [self._u_buffer[-1 - int(n)][i] for i, n in enumerate(self._delay_samples)]
        )

    def step(self, u: np.ndarray, dt: float, d: np.ndarray | None = None) -> np.ndarray:
        """Advance one sample and return the measured output.

        Order of operations: saturate -> delay -> integrate (zero-order hold on
        the input over the interval) -> measure with noise.
        """
        u_sat = self.saturate(u)
        u_eff = self._delayed_input(u_sat, dt)

        d_vec = np.zeros(self.n_disturbances) if d is None else np.atleast_1d(np.asarray(d, float))
        if d_vec.size < self.n_disturbances:
            d_vec = np.pad(d_vec, (0, self.n_disturbances - d_vec.size))
        if np.any(self._d_delay_samples > 0):
            self._d_buffer.append(d_vec.copy())
            d_vec = np.array(
                [self._d_buffer[-1 - int(n)][i] for i, n in enumerate(self._d_delay_samples)]
            )

        h = dt / self.n_substeps
        x = self.x
        for _ in range(self.n_substeps):
            k1 = self.dynamics(x, u_eff, d_vec)
            k2 = self.dynamics(x + 0.5 * h * k1, u_eff, d_vec)
            k3 = self.dynamics(x + 0.5 * h * k2, u_eff, d_vec)
            k4 = self.dynamics(x + h * k3, u_eff, d_vec)
            x = x + (h / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
        self.x = x
        self.t += dt

        y_now = self.measure()
        if np.any(self._y_delay_samples > 0):
            self._y_buffer.append(y_now)
            y_now = np.array(
                [self._y_buffer[-1 - int(n)][i] for i, n in enumerate(self._y_delay_samples)]
            )
        return y_now

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return f"{type(self).__name__}(n_states={self.n_states}, dead_time={self.dead_time})"
